### ISSUE TITLE
Release Roadmap

### ISSUE THREAD

**Issue by NT-Bourgeois-Iridescence-Technologies** [zPSP-Dev/Zig-PSP#1]
- [x] PSP PRX Generation
- [x] All PSP Userland Library Symbols
- [x] Full `build.zig` build script
- [x] Remove all dependencies on PSPSDK headers & Newlib
- [x] Basic PSP Debug Printing
- [x] Remove dependency on Rust-PSP installs.
- [x] Basic PSP Memory & VRAM Allocator
- [x] Basic Error handling on Main
- [x] Fixup enums
- [x] Panic Support
- [x] Remove C dependencies!
- [x] Documentation for the custom modules.
- [x] Benchmarking
- [x] Include basic examples!
- [x] Self-hosted packing tools
- [x] Remove Reliance on Rust libpsp.a
- [x] Generate function stubs (comptime macros?) 
- [x] Fix ABI issues with >4 arg funcs
- [x] Add all NIDs
- [x] New sceGu
- [x] New sceGum 
- [x] 3D Samples
